version: '3'

services:
  frontend:
    image: sadic
    ports:
      - '8080:8080'
    volumes:
      - /app
    working_dir: /app
    command: 'npm run serve'
  backend:
    image: sadic
    ports:
      - '3000:3000'
    volumes:
      - /app
    working_dir: /app/services/login
    command: 'node jwt'